baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Wille Faler'
theme = 'typo'


[taxonomies]
tag = 'tags'

[params]
# Home meta description
description = "A tech-oriented personal blog curated by Francesco Tomaselli."

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content in markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
I’m Wille, an experienced consultant, software engineer, manager & entrepreneur.

I’m passionate about building, enabling & scaling high-performance teams & organisations, and the technologies that enable them.

Based in the beautiful Canton of Zug, Switzerland, I speak fluent English, Swedish, Finnish & proficient German.
"""


singleDateFormat = '2 Jan 2006'

# Collection to display on home
# homeCollectionTitle = 'Posts'
# homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '02 Jan 2006'

# Breadcrumbs
breadcrumbs = true

showFooter = false 
# footerContent = """Custom"""

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/faler/"

[[params.social]]
name = "twitter"
url = "https://x.com/wfaler"

[[params.social]]
name = "github"
url = "https://github.com/wfaler"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "articles"
url = "/articles"

[[params.menu]]
name = "CV"
url = "/cv"

[[params.menu]]
name = "Personal README"
url = "/readme"

# [[params.menu]]
# name = "tags"
# url = "/tags"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'bw'

# Deploy settings

[[deployment.matchers]]
pattern = "^.+\\.(js|css|svg|ttf|woff2)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg|gif|webp)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[params.giscus]
enable = false
repo = "tomfran/blog"
repoid = "R_kgDOLtSszw"
category = "General"
categoryid = "DIC_kwDOLtSsz84CfLm4"
mapping = "pathname"
theme = "preferred_color_scheme"
